name: Flutter Web Deploy

on:
  push:
    branches:
      - main  # triggers deployment when you push to main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.3'

      - name: Install dependencies
        run: flutter pub get

      - name: Build web
        run: |
          flutter clean
          flutter pub get
          flutter build web

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.PAT_GITHUB }}
          publish_dir: build/web
          publish_branch: main
          external_repository: AK-Bishnu/AK-Bishnu.github.io
          force_orphan: true

